export const CREATE_ANNOTATION = 'CREATE_ANNOTATION';
export const NEW_ANNOTATION = 'NEW_ANNOTATION';
export const TOGGLE_CREATING_ANNOTATION = 'TOGGLE_CREATING_ANNOTATION';
export const RECEIVE_ANNOTATION = 'RECEIVE_ANNOTATION';
export const RECEIVE_ANNOTATIONS = 'RECEIVE_ANNOTATIONS';
export const FETCH_ANNOTATIONS = 'FETCH_ANNOTATIONS';

export const TOGGLE_NEW_COMMENT = 'TOGGLE_NEW_COMMENT';
export const RECEIVE_REPLY = 'RECEIVE_REPLY';
export const UPDATE_ARTICLE_URL = 'UPDATE_ARTICLE_URL';
