// annotations
export const CREATE_ANNOTATION = 'CREATE_ANNOTATION';
export const NEW_ANNOTATION = 'NEW_ANNOTATION';
export const TOGGLE_CREATING_ANNOTATION = 'TOGGLE_CREATING_ANNOTATION';
export const RECEIVE_ANNOTATION = 'RECEIVE_ANNOTATION';
export const RECEIVE_ANNOTATIONS = 'RECEIVE_ANNOTATIONS';
export const FETCH_ANNOTATIONS = 'FETCH_ANNOTATIONS';
export const SELECT_ANNOTATION_GROUPS = 'SELECT_ANNOTATION_GROUPS';
export const DELETE_ANNOTATION = 'DELETE_ANNOTATION';

// comments
export const TOGGLE_NEW_COMMENT = 'TOGGLE_NEW_COMMENT';
export const RECEIVE_REPLY = 'RECEIVE_REPLY';

// articles
export const UPDATE_ARTICLE_URL = 'UPDATE_ARTICLE_URL';

// user
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_AUTH_STATUS = 'UPDATE_AUTH_STATUS';
export const FETCH_USER = 'FETCH_USER';

// groups
export const CREATE_GROUP = 'CREATE_GROUP';
export const RECEIVE_GROUP = 'RECEIVE_GROUP';
export const FILTER_GROUP = 'FILTER_GROUP';
